debug: true
logging:
  level:
    root: debug
server:
  port: 10100
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 1
      max-active: 20
      min-idle: 1
      stat-view-servlet:
        allow: true
      test-on-borrow: true
    password: root
    url: jdbc:mysql://localhost:3306/db_springboot_crm
    username: root
  thymeleaf:
    cache: false